version: 2

build: 
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    post_checkout:
      - pip install pyomo==6.4.1

sphinx: 
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
